name: Basic Output python Example

on:
  workflow_dispatch:

jobs:
  basic-python-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
            
      - name: Run Python script
        run: python hello_world.py
            
