name: Basic Output python Example

# on: [push]

on:
  workflow_dispatch:

jobs:
  basic-python-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/setup-python@v4
          with:
            python-version: '3.9'
      - name: Run Python script
        run: python hello_world.py
            
